package org.example.dbeaver.echarts;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.Set;

/** The JSON is authoritative; the SQL companion is generated from it. */
final class DashboardFiles {
    static final int MAX_BYTES = 1_048_576;
    static final String FORMAT = "dbeaver-echarts-dashboard";
    static final String SUFFIX = ".echarts-dashboard.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    private DashboardFiles() { }

    static JsonObject parse(String text) {
        if (text.getBytes(StandardCharsets.UTF_8).length > MAX_BYTES) {
            throw new IllegalArgumentException("Dashboard JSON exceeds 1 MiB.");
        }
        JsonObject document = JsonParser.parseString(text).getAsJsonObject();
        if (!document.has("schemaVersion") || document.get("schemaVersion").getAsInt() != 1
            || !document.has("widgets") || !document.get("widgets").isJsonArray()
            || (document.has("format") && !FORMAT.equals(JsonFields.string(document, "format")))) {
            throw new IllegalArgumentException("Unsupported ECharts dashboard format.");
        }
        if (document.getAsJsonArray("widgets").size() > 24) {
            throw new IllegalArgumentException("A dashboard supports up to 24 widgets.");
        }
        Set<String> ids = new HashSet<>();
        for (JsonElement element : document.getAsJsonArray("widgets")) {
            JsonObject widget = element.getAsJsonObject();
            String id = JsonFields.string(widget, "id");
            if (id.isBlank() || !ids.add(id)) throw new IllegalArgumentException("Invalid or duplicate widget ID.");
            JsonObject source = widget.getAsJsonObject("source");
            if (source == null || JsonFields.string(source, "sql").isBlank()) {
                throw new IllegalArgumentException("Widget \"" + JsonFields.string(widget, "title") + "\" has no SQL. Assign it in Edit.");
            }
            source.addProperty("kind", "savedQuery");
            JsonObject policy = widget.getAsJsonObject("refreshPolicy");
            if (policy != null && "onResult".equals(JsonFields.string(policy, "mode"))) policy.addProperty("mode", "manual");
        }
        document.addProperty("format", FORMAT);
        return document;
    }

    static String read(Path file) throws IOException {
        if (Files.size(file) > MAX_BYTES) throw new IOException("Dashboard JSON exceeds 1 MiB.");
        return GSON.toJson(parse(Files.readString(file, StandardCharsets.UTF_8)));
    }

    static String canonical(String text) { return GSON.toJson(parse(text)); }

    static String sqlDocument(JsonObject document) {
        StringBuilder sql = new StringBuilder("-- ECharts dashboard: " + comment(JsonFields.string(document, "title"))
            + "\n-- Generated from JSON. Edit widget queries with the dashboard Edit button.\n\n");
        for (JsonElement element : document.getAsJsonArray("widgets")) {
            JsonObject widget = element.getAsJsonObject();
            JsonObject source = widget.getAsJsonObject("source");
            sql.append("-- Widget: ").append(comment(JsonFields.string(widget, "title"))).append(" [")
                .append(comment(JsonFields.string(widget, "id"))).append("]\n-- Connection: ")
                .append(comment(JsonFields.string(source, "project"))).append(" / ")
                .append(comment(JsonFields.string(source, "connection"))).append('\n');
            String query = JsonFields.string(source, "sql");
            sql.append(query).append(query.stripTrailing().endsWith(";") ? "\n\n" : "\n;\n\n");
        }
        return sql.toString();
    }

    private static String comment(String text) { return text.replace('\r', ' ').replace('\n', ' '); }

    static void write(Path file, String text) throws IOException {
        JsonObject document = parse(text); // Validate before touching either file.
        String json = GSON.toJson(document) + "\n";
        if (json.getBytes(StandardCharsets.UTF_8).length > MAX_BYTES) throw new IOException("Dashboard JSON exceeds 1 MiB.");
        DocumentFiles.writeWithSqlCompanion(file, json, sqlDocument(document), "-- ECharts dashboard: ",
            "The SQL companion already exists and was not generated by ECharts. Choose another name.");
    }
}
